=== API-Automation-2021v1/bdd-api-tests/src/test/resources/schemas/trello/getTrelloCardSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "required": [
    "id",
    "checkItemStates",
    "closed",
    "dateLastActivity",
    "desc",
    "descData",
    "dueReminder",
    "idBoard",
    "idList",
    "idMembersVoted",
    "idShort",
    "idAttachmentCover",
    "idLabels",
    "manualCoverAttachment",
    "name",
    "pos",
    "shortLink",
    "isTemplate",
    "cardRole",
    "dueComplete",
    "due",
    "email",
    "labels",
    "shortUrl",
    "start",
    "url",
    "idMembers",
    "idChecklists",
    "badges",
    "subscribed",
    "cover"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "string"
    },
    "checkItemStates": {
      "$id": "#/properties/checkItemStates",
      "type": "array",
      "items": {
        "$id": "#/properties/checkItemStates/items"
      }
    },
    "closed": {
      "$id": "#/properties/closed",
      "type": "boolean"
    },
    "dateLastActivity": {
      "$id": "#/properties/dateLastActivity",
      "type": "string"
    },
    "desc": {
      "$id": "#/properties/desc",
      "type": "string"
    },
    "descData": {
      "$id": "#/properties/descData",
      "type": "null"
    },
    "dueReminder": {
      "$id": "#/properties/dueReminder",
      "type": "null"
    },
    "idBoard": {
      "$id": "#/properties/idBoard",
      "type": "string"
    },
    "idList": {
      "$id": "#/properties/idList",
      "type": "string"
    },
    "idMembersVoted": {
      "$id": "#/properties/idMembersVoted",
      "type": "array",
      "items": {
        "$id": "#/properties/idMembersVoted/items"
      }
    },
    "idShort": {
      "$id": "#/properties/idShort",
      "type": "integer"
    },
    "idAttachmentCover": {
      "$id": "#/properties/idAttachmentCover",
      "type": "null"
    },
    "idLabels": {
      "$id": "#/properties/idLabels",
      "type": "array",
      "items": {
        "$id": "#/properties/idLabels/items"
      }
    },
    "manualCoverAttachment": {
      "$id": "#/properties/manualCoverAttachment",
      "type": "boolean"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string"
    },
    "pos": {
      "$id": "#/properties/pos",
      "type": "integer"
    },
    "shortLink": {
      "$id": "#/properties/shortLink",
      "type": "string"
    },
    "isTemplate": {
      "$id": "#/properties/isTemplate",
      "type": "boolean"
    },
    "cardRole": {
      "$id": "#/properties/cardRole",
      "type": "null"
    },
    "dueComplete": {
      "$id": "#/properties/dueComplete",
      "type": "boolean"
    },
    "due": {
      "$id": "#/properties/due",
      "type": "null"
    },
    "email": {
      "$id": "#/properties/email",
      "type": "null"
    },
    "labels": {
      "$id": "#/properties/labels",
      "type": "array",
      "items": {
        "$id": "#/properties/labels/items"
      }
    },
    "shortUrl": {
      "$id": "#/properties/shortUrl",
      "type": "string"
    },
    "start": {
      "$id": "#/properties/start",
      "type": "null"
    },
    "url": {
      "$id": "#/properties/url",
      "type": "string"
    },
    "idMembers": {
      "$id": "#/properties/idMembers",
      "type": "array",
      "items": {
        "$id": "#/properties/idMembers/items"
      }
    },
    "idChecklists": {
      "$id": "#/properties/idChecklists",
      "type": "array",
      "items": {
        "$id": "#/properties/idChecklists/items"
      }
    },
    "badges": {
      "$id": "#/properties/badges",
      "type": "object",
      "required": [
        "attachmentsByType",
        "location",
        "votes",
        "viewingMemberVoted",
        "subscribed",
        "fogbugz",
        "checkItems",
        "checkItemsChecked",
        "checkItemsEarliestDue",
        "comments",
        "attachments",
        "description",
        "due",
        "dueComplete",
        "start"
      ],
      "properties": {
        "attachmentsByType": {
          "$id": "#/properties/badges/properties/attachmentsByType",
          "type": "object",
          "required": [
            "trello"
          ],
          "properties": {
            "trello": {
              "$id": "#/properties/badges/properties/attachmentsByType/properties/trello",
              "type": "object",
              "required": [
                "board",
                "card"
              ],
              "properties": {
                "board": {
                  "$id": "#/properties/badges/properties/attachmentsByType/properties/trello/properties/board",
                  "type": "integer"
                },
                "card": {
                  "$id": "#/properties/badges/properties/attachmentsByType/properties/trello/properties/card",
                  "type": "integer"
                }
              }
            }
          }
        },
        "location": {
          "$id": "#/properties/badges/properties/location",
          "type": "boolean"
        },
        "votes": {
          "$id": "#/properties/badges/properties/votes",
          "type": "integer"
        },
        "viewingMemberVoted": {
          "$id": "#/properties/badges/properties/viewingMemberVoted",
          "type": "boolean"
        },
        "subscribed": {
          "$id": "#/properties/badges/properties/subscribed",
          "type": "boolean"
        },
        "fogbugz": {
          "$id": "#/properties/badges/properties/fogbugz",
          "type": "string"
        },
        "checkItems": {
          "$id": "#/properties/badges/properties/checkItems",
          "type": "integer"
        },
        "checkItemsChecked": {
          "$id": "#/properties/badges/properties/checkItemsChecked",
          "type": "integer"
        },
        "checkItemsEarliestDue": {
          "$id": "#/properties/badges/properties/checkItemsEarliestDue",
          "type": "null"
        },
        "comments": {
          "$id": "#/properties/badges/properties/comments",
          "type": "integer"
        },
        "attachments": {
          "$id": "#/properties/badges/properties/attachments",
          "type": "integer"
        },
        "description": {
          "$id": "#/properties/badges/properties/description",
          "type": "boolean"
        },
        "due": {
          "$id": "#/properties/badges/properties/due",
          "type": "null"
        },
        "dueComplete": {
          "$id": "#/properties/badges/properties/dueComplete",
          "type": "boolean"
        },
        "start": {
          "$id": "#/properties/badges/properties/start",
          "type": "null"
        }
      }
    },
    "subscribed": {
      "$id": "#/properties/subscribed",
      "type": "boolean"
    },
    "cover": {
      "$id": "#/properties/cover",
      "type": "object",
      "required": [
        "idAttachment",
        "color",
        "idUploadedBackground",
        "size",
        "brightness",
        "idPlugin"
      ],
      "properties": {
        "idAttachment": {
          "$id": "#/properties/cover/properties/idAttachment",
          "type": "null"
        },
        "color": {
          "$id": "#/properties/cover/properties/color",
          "type": "null"
        },
        "idUploadedBackground": {
          "$id": "#/properties/cover/properties/idUploadedBackground",
          "type": "null"
        },
        "size": {
          "$id": "#/properties/cover/properties/size",
          "type": "string"
        },
        "brightness": {
          "$id": "#/properties/cover/properties/brightness",
          "type": "string"
        },
        "idPlugin": {
          "$id": "#/properties/cover/properties/idPlugin",
          "type": "null"
        }
      }
    }
  }
}

=== API-Automation-2021v1/bdd-api-tests/src/test/resources/schemas/trello/putTrelloCardSchema.json
{
  "id": "60b98b58062f238eb166d12c",
  "checkItemStates": [],
  "closed": false,
  "dateLastActivity": "2021-06-04T02:10:57.197Z",
  "desc": "Updating description",
  "descData": {
    "emoji": {}
  },
  "dueReminder": null,
  "idBoard": "60b4542ff34e693aa42ced74",
  "idList": "60b455db13e5d41a9ac0176f",
  "idMembersVoted": [],
  "idShort": 6,
  "idAttachmentCover": null,
  "idLabels": [],
  "manualCoverAttachment": false,
  "name": "Updating Name Card",
  "pos": 81920,
  "shortLink": "PhnWTfq0",
  "isTemplate": false,
  "cardRole": null,
  "dueComplete": false,
  "due": null,
  "email": null,
  "labels": [],
  "shortUrl": "https://trello.com/c/PhnWTfq0",
  "start": null,
  "url": "https://trello.com/c/PhnWTfq0/6-updating-name-card",
  "cover": {
    "idAttachment": null,
    "color": null,
    "idUploadedBackground": null,
    "size": "normal",
    "brightness": "dark",
    "idPlugin": null
  },
  "idMembers": [],
  "badges": {
    "attachmentsByType": {
      "trello": {
        "board": 0,
        "card": 0
      }
    },
    "location": false,
    "votes": 0,
    "viewingMemberVoted": false,
    "subscribed": false,
    "fogbugz": "",
    "checkItems": 0,
    "checkItemsChecked": 0,
    "checkItemsEarliestDue": null,
    "comments": 0,
    "attachments": 0,
    "description": true,
    "due": null,
    "dueComplete": false,
    "start": null
  },
  "subscribed": false,
  "idChecklists": []
}
